# Generated by Django 3.1.7 on 2021-03-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_queries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
