# Generated by Django 3.1.7 on 2021-03-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='number_of_items',
        ),
    ]
