# Generated by Django 3.1.7 on 2021-03-24 13:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('first_name', 'last_name', 'country'),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('annotation', models.TextField(blank=True, max_length=250, null=True)),
                ('publishing_house', models.CharField(max_length=250)),
                ('isbn', models.IntegerField(unique=True)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2021)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.author')),
            ],
            options={
                'ordering': ('title', 'year', 'price', 'publishing_house'),
            },
        ),
    ]
